import {cpSync,existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,statSync,utimesSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process'; import {tmpdir} from 'node:os'; import {basename,dirname,join} from 'node:path'; import {fileURLToPath} from 'node:url'; import {createHash} from 'node:crypto';
const root=dirname(fileURLToPath(import.meta.url)), epoch=new Date('2000-01-01T00:00:00Z');
const walk=(dir,rel='')=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=rel?`${rel}/${e.name}`:e.name, full=join(dir,e.name);if(e.isSymbolicLink())throw Error(`symbolic link: ${f}`);return e.isDirectory()?walk(full,f):e.isFile()?[f]:[]});
const copy=(from,to,files)=>files.forEach(f=>{const out=join(to,f);mkdirSync(dirname(out),{recursive:true});cpSync(join(from,f),out);utimesSync(out,epoch,epoch)});
const zip=(cwd,out,files)=>execFileSync('zip',['-X','-q',out,...files],{cwd,env:{...process.env,TZ:'UTC'}});const hash=f=>createHash('sha256').update(readFileSync(f)).digest('hex');
const manifest=JSON.parse(readFileSync(join(root,'ipollowork.plugin.json'))); if(manifest.schemaVersion!==2||manifest.source.trusted!==false||manifest.resources.length!==1)throw Error('invalid manifest');
const stem=`${manifest.id}-${manifest.package.version}`,dist=join(root,'dist');mkdirSync(dist,{recursive:true});const stage=mkdtempSync(join(tmpdir(),'rollout-card-'));
try {const pluginFiles=['ipollowork.plugin.json',...walk(join(root,'skills'),'skills')];copy(root,stage,pluginFiles);const plugin=join(dist,`${stem}.ipollowork-plugin`);rmSync(plugin,{force:true});zip(stage,plugin,pluginFiles);if(!existsSync(plugin)||statSync(plugin).size>12*1024*1024)throw Error('plugin archive invalid');const skillStage=mkdtempSync(join(tmpdir(),'rollout-card-skill-'));try{const files=walk(join(root,'skills/model-rollout-card'));copy(join(root,'skills/model-rollout-card'),skillStage,files);const skill=join(dist,`${stem}-skill.zip`);rmSync(skill,{force:true});zip(skillStage,skill,files);const sourceStage=mkdtempSync(join(tmpdir(),'rollout-card-source-'));try{const sourceFiles=walk(root).filter(f=>!f.startsWith('dist/')&&!f.startsWith('.git/'));const prefix=`${stem}-source`;copy(root,join(sourceStage,prefix),sourceFiles);const source=join(dist,`${stem}-source.zip`);rmSync(source,{force:true});zip(sourceStage,source,sourceFiles.map(f=>`${prefix}/${f}`));writeFileSync(join(dist,'SHA256SUMS.txt'),`${hash(plugin)}  ${basename(plugin)}\n${hash(skill)}  ${basename(skill)}\n${hash(source)}  ${basename(source)}\n`)}finally{rmSync(sourceStage,{recursive:true,force:true})}}finally{rmSync(skillStage,{recursive:true,force:true})}}finally{rmSync(stage,{recursive:true,force:true})}
